[[language]]
name = "typescript"
shebangs = ["deno"]
roots = ["deno.json", "deno.jsonc"]
file-types = ["js", "ts", "jsx", "tsx"]
language-servers = ["deno-lsp"]
formatter = { command = "deno", args = ["fmt", "-"]}
auto-format = true

[[language]]
name = "tsx"
language-id = "typescriptreact"
file-types = ["tsx"]
language-servers = [ "deno-lsp" ]
formatter = { command = "deno", args = ["fmt", "-"]}
auto-format = true

[[language]]
name = "jsx"
language-id = "javascriptreact"
file-types = ["jsx"]
language-servers = [ "deno-lsp" ]
formatter = { command = "deno", args = ["fmt", "-"]}
auto-format = true

[[language]]
name = "javascript"
language-id = "javascript"
file-types = ["js"]
language-servers = [ "deno-lsp" ]
formatter = { command = "deno", args = ["fmt", "-"]}
auto-format = true

[language-server.deno-lsp]
command = "deno"
args = ["lsp"]
environment = { NO_COLOR = "1" }

[language-server.deno-lsp.config.deno]
enable = true
unstable = true
